# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "gomod" # See documentation for possible values
    directory: "/" # Location of package manifests
    registries:
      - github-fusion
    schedule:
      interval: "daily"
    target-branch: "main"
    groups:
      all-dependencies:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: "/cmd/api-server"
    schedule:
      interval: "daily"
    target-branch: "main"
    groups:
      all-dependencies:
        patterns:
          - "*"

registries:
  github-fusion:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{secrets.ORG_GITHUB_PAT}}