---
run:
  allow-parallel-runners: true
  skip-dirs:
    - "api"
    - "mocks"
  skip-files:
    - "internal/.*/.*_test.go"
  timeout: 5m

issues:
  exclude-use-default: false

output:
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters:
  disable-all: true
  enable:
    - bodyclose
    - cyclop
    # - deadcode
    - dupl
    - errcheck
    - errorlint
    - exhaustive
    - gci
    - goconst
    - gocritic
    - godot
    - gocognit
    - gofmt
    - gofumpt
    - goimports
    - gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    # - ifshort
    - importas
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nestif
    # - noctx
    - nolintlint
    # - prealloc
    - predeclared
    - revive
    - staticcheck
    # - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    # - varcheck
    - whitespace
    - wsl

linters-settings:
  cyclop:
    max-complexity: 10
    package-average: 0.0
    skip-tests: false
  errcheck:
    check-type-assertions: true
    check-blank: true
  gci:
    custom-order: true
    sections:
      - standard
      - default
      - prefix(github.com/logicnow)
      - prefix(github.com/nable-fusion)
      - prefix(github.com/nable-fusion/test-automation-lib-go)
      - dot
  gocognit:
    min-complexity: 10
  goconst:
    min-len: 3
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - performance
      - diagnostic
      - style
      - experimental
      - opinionated
  godot:
    check-all: true
  gosec:
    excludes:
      - G102
  govet:
    check-shadowing: true
    enable-all: true
  misspell:
    locale: UK
  nestif:
    min-complexity: 4
  nolintlint:
    allow-unused: false
    allow-no-explanation: []
    require-explanation: true
    require-specific: true
  revive:
    rules:
      - name: dot-imports
        severity: warning
        disabled: true
  stylecheck:
    checks:
      - all
      - -ST1000
      - -ST1003
    dot-import-whitelist:
      - github.com/onsi/ginkgo/v2
      - github.com/onsi/gomega
  wsl:
    allow-trailing-comment: true
