kind: Service
apiVersion: v1
metadata:
  name: api-template-service
  labels:
    app: api-template-service
    service: api-template-service
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
  selector:
    app: api-template-deploy
  type: ClusterIP
