apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

replicas:
  - name: api-template-deploy
    count: 1

configMapGenerator:
  - name: api-template-config
    behavior: merge
    literals:
      - AWS_REGION=eu-west-1
  - name: api-template-vars
    namespace: fusion-api-template
    behavior: merge
    literals:
      - API_HOST="api-template.stg.cdo.system-monitor.com"

patches:
  - target:
      kind: Deployment
      name: api-template-deploy
    patch: |-
      - op: replace
        path: "/spec/template/metadata/annotations/splunk.com~1index"
        value: p-fusion-stg
