apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fusion-api-template

resources:
  - resources/deployment.yaml
  - resources/service.yaml
  - resources/service-account.yaml
  - resources/horizontal-pod-autoscaler.yaml
  - resources/pod-disruption-budget.yaml
  - istio/authorization-policy.yaml
  - istio/destination-rule.yaml
  - istio/gateway.yaml
  - istio/virtual-service.yaml

configMapGenerator:
  - name: api-template-config
    behavior: create
    literals:
      - FUSION_ENV=
      - GO_OPTIONS=
