apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-template-cert
  namespace: istio-system
  labels:
    use-istio-ingress: "true"
    use-dns01-challenge: "true"
spec:
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: api-template-cert
  commonName: $(API_HOST)
  dnsNames:
    - $(API_HOST)