// Code generated by mockery v2.30.0. DO NOT EDIT.

package mocks

import (
	context "context"

	v1 "github.com/nable-fusion/fusion-api-template/api/v1"
	mock "github.com/stretchr/testify/mock"
)

// ClientWithResponsesInterface is an autogenerated mock type for the ClientWithResponsesInterface type
type ClientWithResponsesInterface struct {
	mock.Mock
}

type ClientWithResponsesInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *ClientWithResponsesInterface) EXPECT() *ClientWithResponsesInterface_Expecter {
	return &ClientWithResponsesInterface_Expecter{mock: &_m.Mock}
}

// GetHealthCheckWithResponse provides a mock function with given fields: ctx, reqEditors
func (_m *ClientWithResponsesInterface) GetHealthCheckWithResponse(ctx context.Context, reqEditors ...v1.RequestEditorFn) (*v1.GetHealthCheckResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *v1.GetHealthCheckResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...v1.RequestEditorFn) (*v1.GetHealthCheckResponse, error)); ok {
		return rf(ctx, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...v1.RequestEditorFn) *v1.GetHealthCheckResponse); ok {
		r0 = rf(ctx, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.GetHealthCheckResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...v1.RequestEditorFn) error); ok {
		r1 = rf(ctx, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClientWithResponsesInterface_GetHealthCheckWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHealthCheckWithResponse'
type ClientWithResponsesInterface_GetHealthCheckWithResponse_Call struct {
	*mock.Call
}

// GetHealthCheckWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - reqEditors ...v1.RequestEditorFn
func (_e *ClientWithResponsesInterface_Expecter) GetHealthCheckWithResponse(ctx interface{}, reqEditors ...interface{}) *ClientWithResponsesInterface_GetHealthCheckWithResponse_Call {
	return &ClientWithResponsesInterface_GetHealthCheckWithResponse_Call{Call: _e.mock.On("GetHealthCheckWithResponse",
		append([]interface{}{ctx}, reqEditors...)...)}
}

func (_c *ClientWithResponsesInterface_GetHealthCheckWithResponse_Call) Run(run func(ctx context.Context, reqEditors ...v1.RequestEditorFn)) *ClientWithResponsesInterface_GetHealthCheckWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]v1.RequestEditorFn, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(v1.RequestEditorFn)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *ClientWithResponsesInterface_GetHealthCheckWithResponse_Call) Return(_a0 *v1.GetHealthCheckResponse, _a1 error) *ClientWithResponsesInterface_GetHealthCheckWithResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClientWithResponsesInterface_GetHealthCheckWithResponse_Call) RunAndReturn(run func(context.Context, ...v1.RequestEditorFn) (*v1.GetHealthCheckResponse, error)) *ClientWithResponsesInterface_GetHealthCheckWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// GetWelcomePageWithResponse provides a mock function with given fields: ctx, reqEditors
func (_m *ClientWithResponsesInterface) GetWelcomePageWithResponse(ctx context.Context, reqEditors ...v1.RequestEditorFn) (*v1.GetWelcomePageResponse, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *v1.GetWelcomePageResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...v1.RequestEditorFn) (*v1.GetWelcomePageResponse, error)); ok {
		return rf(ctx, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...v1.RequestEditorFn) *v1.GetWelcomePageResponse); ok {
		r0 = rf(ctx, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.GetWelcomePageResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...v1.RequestEditorFn) error); ok {
		r1 = rf(ctx, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClientWithResponsesInterface_GetWelcomePageWithResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWelcomePageWithResponse'
type ClientWithResponsesInterface_GetWelcomePageWithResponse_Call struct {
	*mock.Call
}

// GetWelcomePageWithResponse is a helper method to define mock.On call
//   - ctx context.Context
//   - reqEditors ...v1.RequestEditorFn
func (_e *ClientWithResponsesInterface_Expecter) GetWelcomePageWithResponse(ctx interface{}, reqEditors ...interface{}) *ClientWithResponsesInterface_GetWelcomePageWithResponse_Call {
	return &ClientWithResponsesInterface_GetWelcomePageWithResponse_Call{Call: _e.mock.On("GetWelcomePageWithResponse",
		append([]interface{}{ctx}, reqEditors...)...)}
}

func (_c *ClientWithResponsesInterface_GetWelcomePageWithResponse_Call) Run(run func(ctx context.Context, reqEditors ...v1.RequestEditorFn)) *ClientWithResponsesInterface_GetWelcomePageWithResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]v1.RequestEditorFn, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(v1.RequestEditorFn)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *ClientWithResponsesInterface_GetWelcomePageWithResponse_Call) Return(_a0 *v1.GetWelcomePageResponse, _a1 error) *ClientWithResponsesInterface_GetWelcomePageWithResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClientWithResponsesInterface_GetWelcomePageWithResponse_Call) RunAndReturn(run func(context.Context, ...v1.RequestEditorFn) (*v1.GetWelcomePageResponse, error)) *ClientWithResponsesInterface_GetWelcomePageWithResponse_Call {
	_c.Call.Return(run)
	return _c
}

// NewClientWithResponsesInterface creates a new instance of ClientWithResponsesInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClientWithResponsesInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClientWithResponsesInterface {
	mock := &ClientWithResponsesInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
