// Code generated by mockery v2.30.0. DO NOT EDIT.

package mocks

import (
	context "context"
	http "net/http"

	mock "github.com/stretchr/testify/mock"

	v1 "github.com/nable-fusion/fusion-api-template/api/v1"
)

// ClientInterface is an autogenerated mock type for the ClientInterface type
type ClientInterface struct {
	mock.Mock
}

type ClientInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *ClientInterface) EXPECT() *ClientInterface_Expecter {
	return &ClientInterface_Expecter{mock: &_m.Mock}
}

// GetHealthCheck provides a mock function with given fields: ctx, reqEditors
func (_m *ClientInterface) GetHealthCheck(ctx context.Context, reqEditors ...v1.RequestEditorFn) (*http.Response, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *http.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...v1.RequestEditorFn) (*http.Response, error)); ok {
		return rf(ctx, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...v1.RequestEditorFn) *http.Response); ok {
		r0 = rf(ctx, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...v1.RequestEditorFn) error); ok {
		r1 = rf(ctx, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClientInterface_GetHealthCheck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHealthCheck'
type ClientInterface_GetHealthCheck_Call struct {
	*mock.Call
}

// GetHealthCheck is a helper method to define mock.On call
//   - ctx context.Context
//   - reqEditors ...v1.RequestEditorFn
func (_e *ClientInterface_Expecter) GetHealthCheck(ctx interface{}, reqEditors ...interface{}) *ClientInterface_GetHealthCheck_Call {
	return &ClientInterface_GetHealthCheck_Call{Call: _e.mock.On("GetHealthCheck",
		append([]interface{}{ctx}, reqEditors...)...)}
}

func (_c *ClientInterface_GetHealthCheck_Call) Run(run func(ctx context.Context, reqEditors ...v1.RequestEditorFn)) *ClientInterface_GetHealthCheck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]v1.RequestEditorFn, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(v1.RequestEditorFn)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *ClientInterface_GetHealthCheck_Call) Return(_a0 *http.Response, _a1 error) *ClientInterface_GetHealthCheck_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClientInterface_GetHealthCheck_Call) RunAndReturn(run func(context.Context, ...v1.RequestEditorFn) (*http.Response, error)) *ClientInterface_GetHealthCheck_Call {
	_c.Call.Return(run)
	return _c
}

// GetWelcomePage provides a mock function with given fields: ctx, reqEditors
func (_m *ClientInterface) GetWelcomePage(ctx context.Context, reqEditors ...v1.RequestEditorFn) (*http.Response, error) {
	_va := make([]interface{}, len(reqEditors))
	for _i := range reqEditors {
		_va[_i] = reqEditors[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *http.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...v1.RequestEditorFn) (*http.Response, error)); ok {
		return rf(ctx, reqEditors...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...v1.RequestEditorFn) *http.Response); ok {
		r0 = rf(ctx, reqEditors...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...v1.RequestEditorFn) error); ok {
		r1 = rf(ctx, reqEditors...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ClientInterface_GetWelcomePage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWelcomePage'
type ClientInterface_GetWelcomePage_Call struct {
	*mock.Call
}

// GetWelcomePage is a helper method to define mock.On call
//   - ctx context.Context
//   - reqEditors ...v1.RequestEditorFn
func (_e *ClientInterface_Expecter) GetWelcomePage(ctx interface{}, reqEditors ...interface{}) *ClientInterface_GetWelcomePage_Call {
	return &ClientInterface_GetWelcomePage_Call{Call: _e.mock.On("GetWelcomePage",
		append([]interface{}{ctx}, reqEditors...)...)}
}

func (_c *ClientInterface_GetWelcomePage_Call) Run(run func(ctx context.Context, reqEditors ...v1.RequestEditorFn)) *ClientInterface_GetWelcomePage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]v1.RequestEditorFn, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(v1.RequestEditorFn)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *ClientInterface_GetWelcomePage_Call) Return(_a0 *http.Response, _a1 error) *ClientInterface_GetWelcomePage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ClientInterface_GetWelcomePage_Call) RunAndReturn(run func(context.Context, ...v1.RequestEditorFn) (*http.Response, error)) *ClientInterface_GetWelcomePage_Call {
	_c.Call.Return(run)
	return _c
}

// NewClientInterface creates a new instance of ClientInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClientInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClientInterface {
	mock := &ClientInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
