// Code generated by mockery v2.30.0. DO NOT EDIT.

package mocks

import (
	v1 "github.com/nable-fusion/fusion-api-template/api/v1"
	mock "github.com/stretchr/testify/mock"
)

// ClientOption is an autogenerated mock type for the ClientOption type
type ClientOption struct {
	mock.Mock
}

type ClientOption_Expecter struct {
	mock *mock.Mock
}

func (_m *ClientOption) EXPECT() *ClientOption_Expecter {
	return &ClientOption_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0
func (_m *ClientOption) Execute(_a0 *v1.Client) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*v1.Client) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ClientOption_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type ClientOption_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 *v1.Client
func (_e *ClientOption_Expecter) Execute(_a0 interface{}) *ClientOption_Execute_Call {
	return &ClientOption_Execute_Call{Call: _e.mock.On("Execute", _a0)}
}

func (_c *ClientOption_Execute_Call) Run(run func(_a0 *v1.Client)) *ClientOption_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*v1.Client))
	})
	return _c
}

func (_c *ClientOption_Execute_Call) Return(_a0 error) *ClientOption_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ClientOption_Execute_Call) RunAndReturn(run func(*v1.Client) error) *ClientOption_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewClientOption creates a new instance of ClientOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClientOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClientOption {
	mock := &ClientOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
