// Code generated by mockery v2.30.0. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// ServerInterface is an autogenerated mock type for the ServerInterface type
type ServerInterface struct {
	mock.Mock
}

type ServerInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *ServerInterface) EXPECT() *ServerInterface_Expecter {
	return &ServerInterface_Expecter{mock: &_m.Mock}
}

// GetHealthCheck provides a mock function with given fields: ctx
func (_m *ServerInterface) GetHealthCheck(ctx echo.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ServerInterface_GetHealthCheck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHealthCheck'
type ServerInterface_GetHealthCheck_Call struct {
	*mock.Call
}

// GetHealthCheck is a helper method to define mock.On call
//   - ctx echo.Context
func (_e *ServerInterface_Expecter) GetHealthCheck(ctx interface{}) *ServerInterface_GetHealthCheck_Call {
	return &ServerInterface_GetHealthCheck_Call{Call: _e.mock.On("GetHealthCheck", ctx)}
}

func (_c *ServerInterface_GetHealthCheck_Call) Run(run func(ctx echo.Context)) *ServerInterface_GetHealthCheck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context))
	})
	return _c
}

func (_c *ServerInterface_GetHealthCheck_Call) Return(_a0 error) *ServerInterface_GetHealthCheck_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServerInterface_GetHealthCheck_Call) RunAndReturn(run func(echo.Context) error) *ServerInterface_GetHealthCheck_Call {
	_c.Call.Return(run)
	return _c
}

// GetWelcomePage provides a mock function with given fields: ctx
func (_m *ServerInterface) GetWelcomePage(ctx echo.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ServerInterface_GetWelcomePage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWelcomePage'
type ServerInterface_GetWelcomePage_Call struct {
	*mock.Call
}

// GetWelcomePage is a helper method to define mock.On call
//   - ctx echo.Context
func (_e *ServerInterface_Expecter) GetWelcomePage(ctx interface{}) *ServerInterface_GetWelcomePage_Call {
	return &ServerInterface_GetWelcomePage_Call{Call: _e.mock.On("GetWelcomePage", ctx)}
}

func (_c *ServerInterface_GetWelcomePage_Call) Run(run func(ctx echo.Context)) *ServerInterface_GetWelcomePage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context))
	})
	return _c
}

func (_c *ServerInterface_GetWelcomePage_Call) Return(_a0 error) *ServerInterface_GetWelcomePage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServerInterface_GetWelcomePage_Call) RunAndReturn(run func(echo.Context) error) *ServerInterface_GetWelcomePage_Call {
	_c.Call.Return(run)
	return _c
}

// NewServerInterface creates a new instance of ServerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServerInterface {
	mock := &ServerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
