apiVersion: v1
kind: Service
metadata:
  name: localstack
spec:
  selector:
    app: localstack
  ports:
    - port: 4566
      protocol: TCP
      name: localstack
      targetPort: 4566
    - port: 4510
      protocol: TCP
      name: redis
      targetPort: 4510
  type: ClusterIP